#!/bin/bash

if [ -z "$*" ]
	then echo "no arguments" 
		exit 1
fi

#create tree-like maven structure
mkdir -p ~/IdeaProjects/"$*"/src/{main,test}/java/pl/michalak/adam

#create files at src and test 
touch ~/IdeaProjects/"$*"/src/{main/java/pl/michalak/adam/App.java,test/java/pl/michalak/adam/AppTest.java}
cd ~/IdeaProjects/"$*"/

#add staff to App.java and AppTest.java
cat <<-EOF > ~/IdeaProjects/"$*"/src/main/java/pl/michalak/adam/App.java
package pl.michalak.adam;

class App{
public static void main(String[] args) {

}
}
EOF

#ask for project description
read -p "Podaj krótki opis projektu: " description

#add minimal pom.xml
set +x
curl https://gist.githubusercontent.com/LIttleAncientForestKami/c9b185c123fc97f6022861f645766aa5/raw/45db276f570fcca357fbcf36b6209517c69c6427/pom.xml | sed s/pl.lafk/pl.michalak.adam/g | sed s/#APP/java.academy/g | sed s/#NAME/"$*"/g | sed s/#DESC/"$description"/g > pom.xml
#create gitignore

curl https://www.gitignore.io/api/java,intellij > .gitignore
echo ".*iml" >> .gitignore

#Initialize empty git repository in the project's folder
git init

#Add empty readme.md file with a project name
touch README.md
echo "${*^^}" >> README.md
cat <<-EOF >> README.md

$description
EOF






