#!/bin/bash

if [ -z "$*" ]
	then echo "no arguments" 
		exit 1
fi
#create tree-like maven structure
mkdir -p "$*"/{src,test}/main/java
#create files at src and test 
touch "$*"/{src/main/java/App.java,test/main/java/tests.java}
#add minimal pom.xml
cd "$*"
cat >pom.xml<<EOF
<?xml version=1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" 
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
        http://maven.apache.org/xsd/maven-4.0.0.xsd">
         <modelVersion>4.0.0</modelVersion>
 
         <groupId>com.mycompany.app</groupId>
         <artifactId>my-app</artifactId>
         <version>1.0-SNAPSHOT</version>
         <name>#NAME</name> 
         <description>#DESC</description>
 </project>
EOF
#add minimal gitignore file 
cat >.gitignore<<EOF2
#major cases for intellij IDEA

*.iml
*.xml

EOF2









