#!/bin/bash

if [ -z "$*" ]
	then echo "no arguments" 
		exit 1
fi

#create tree-like maven structure
mkdir -p ~/IdeaProjects/"$*"/src/{main,test}/java/pl/michalak/adam

#create files at src and test 
touch ~/IdeaProjects/"$*"/src/{main/java/pl/michalak/adam/$*.java,test/java/pl/michalak/adam/$*Test.java}
cd ~/IdeaProjects/"$*"/

#add staff to App.java and AppTest.java
cat <<-EOF > ~/IdeaProjects/"$*"/src/main/java/pl/michalak/adam/$*.java
package pl.michalak.adam;
/**
 * Główna klasa programu
 *
 * @author Adam Michalak
 */
class $* {
public static void main(String[] args) {

    }
}
EOF

#ask for project description
read -p "Podaj krótki opis projektu: " description

#add minimal pom.xml
set +x
curl https://gist.githubusercontent.com/LIttleAncientForestKami/c9b185c123fc97f6022861f645766aa5/raw/45db276f570fcca357fbcf36b6209517c69c6427/pom.xml | sed s/pl.lafk/pl.michalak.adam/g | sed s/#APP/java.academy/g | sed s/#NAME/"$*"/g | sed s/#DESC/"$description"/g > pom.xml
#create gitignore

curl https://www.gitignore.io/api/java,intellij > .gitignore
echo ".*iml" >> .gitignore

#Initialize empty git repository in the project's folder
git init

#Add readme.md file with a project name and description
touch README.md
#echo "${*^^}" >> README.md
cat <<-EOF >> README.md
${*^^}

$description
EOF

#Add estymaty.md for future goal specification
cat <<-EOF >> estymaty.md
# $*
#
# $description
|Data  |Pesymistyczna|Realistyczna|Optymistyczna|
:-------------------:|:-------------------:|:-------------------|-------------------:
EOF

#Enable user to add remote repository
read -p "Do you want to track remote repository?[Y/n] " repoAnswer
if [ "$repoAnswer" = "Y" ] || [ "$repoAnswer" = "" ]
then 
read -p "Feed me with link to the repository: " repoLink 
git remote add origin $repoLink
fi

#recompile pom.xml and create target folder
mvn clean install compile

